### ISSUE TITLE
[css files MimeType not recognized] -> Let's fix this

### ISSUE THREAD

**Issue by rvvergara** [zinagithub/to-do-list#2]
This is what happens when I open the app

![image](https://user-images.githubusercontent.com/6015315/62907414-a65ee080-bda5-11e9-89c7-cf6c2471b11f.png)

There's no way for me to add any task to the default Project (neither can I to any project that I create).

### Addendum:

When I add a new project it appears over at the left side. But I'm wondering why the default "Project" isn't

![image](https://user-images.githubusercontent.com/6015315/62907484-048bc380-bda6-11e9-935c-ec119075b847.png)

**Comment by YellowPipe** [comment]
Everything seems to be working for me.
